

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: express-app

  template: # template for the pods
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-container
        image: nawfel25/memories-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      restartPolicy: Always 


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: memories-frontend
  labels: 
    app: react-deployment
spec:
  selector:
    matchLabels:
      app: memories-frontend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: memories-frontend
    spec:
      containers:
      - name: memories-container 
        image: nawfel25/memories-frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports: 
        - containerPort: 80
      restartPolicy: Always 
--- 
