apiVersion: v1
kind: Service
metadata:
  name: service-backend
  labels:
    run: backend-service 
spec:
  selector:
    app: memories-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
--- 
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  labels:
    run: frontend-service 
spec:
  selector:
    app: memories-frontend
  ports:
    - name: http
      port: 8081
      targetPort: 81
      protocol: TCP

  type: NodePort




      